version: '2'
services:
  emile_web:
    image: odoo
    container_name: emile_odoo_web
    depends_on:
      - emile_db
    ports:
      - "8080:8069"
    environment:
      - HOST=db
      - USER=frazer-odoo
      - PASSWORD=password
      - PORT=5432
    volumes:
      - emile-web-data:/var/lib/odoo

    networks:
      - emile-network

  emile_db:
    image: postgres:10
    container_name: emile_odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=frazer-odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - emile-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - emile-network

networks:
  emile-network:

volumes:
  emile-web-data:
  emile-db-data: